dist: bionic

language: c

addons:
  apt:
    packages:
    - libssl-dev
    - libcurl4-openssl-dev
    - libjansson-dev
    - libhiredis-dev
    - libcjose-dev
    - apache2-dev
    - check
    - memcached
    - redis-server

arch:
  - amd64,
  - ppc64le
  - arm64
  - arm64-graviton2

#  - s390x does not have libcjose-dev
os: linux

env:
  NGINX_VERSION=1.14.0

services:
    - memcached
    - redis-server

install:
  - wget https://nginx.org/download/nginx-${NGINX_VERSION}.tar.gz
  - tar zxvf nginx-${NGINX_VERSION}.tar.gz
  - ln -s nginx-${NGINX_VERSION} nginx
  - cd nginx
  - ./configure --with-cc-opt='-g -O2 -fdebug-prefix-map=/build/nginx-H4cN7P/nginx-${NGINX_VERSION}=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Wdate-time -D_FORTIFY_SOURCE=2' --with-ld-opt='-Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -fPIC' --prefix=/usr/share/nginx --conf-path=/etc/nginx/nginx.conf --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --lock-path=/var/lock/nginx.lock --pid-path=/run/nginx.pid --modules-path=/usr/lib/nginx/modules --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --with-debug --with-pcre-jit --with-http_ssl_module --with-http_stub_status_module --with-http_realip_module --with-http_auth_request_module --with-http_v2_module --with-http_dav_module --with-http_slice_module --with-threads --with-http_addition_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_sub_module --with-stream=dynamic --with-stream_ssl_module --with-mail=dynamic --with-mail_ssl_module
  - cd -

before_script:
  - ./autogen.sh
  - ./configure --with-nginx=${TRAVIS_BUILD_DIR}/nginx

script:
  - make test

after_script:
  - cat test-suite.log
